version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: myvanna-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: myvanna-qdrant
    ports:
      - "${QDRANT_PORT}:6333"
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage
    # restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data: