[tool.poetry]
name = "myvanna"
version = "0.1.0"
description = ""
authors = ["yoshimoriryu <hamzah.chairil98@gmail.com>"]
readme = "README.md"
packages = [{include = "vanna_engine", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
sqlalchemy = "^2.0.43"
psycopg2-binary = "^2.9.10"
openai = "^1.99.9"
vanna = "^0.7.9"
qdrant-client = "^1.15.1"
fastembed = "^0.7.1"
google-generativeai = "^0.8.5"
python-dotenv = "^1.1.1"
google-genai = "^1.30.0"
google-cloud-aiplatform = ">=1.38"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
black = "^25.1.0"

[tool.pytest.ini_options]
pythonpath = "."

[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = false


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"