import os
import sys
from typing import List, TypedDict, Optional
from langchain_core.messages import BaseMessage, HumanMessage
import requests
import pandas as pd
import google.generativeai as genai
from qdrant_client import QdrantClient
from sqlalchemy import create_engine, text
import json
from langgraph.graph import StateGraph, END

# --- Updated Imports ---
from src.vanna_engine import config
from src.vanna_engine.my_vanna import MyVanna


class GraphState(TypedDict):
    """
    Represents the state of our chatbot agent.

    Attributes:
        messages: The entire conversation history.
        next_tool: The tool the router has decided to use next.
        sql_query: The SQL query generated by Vanna.
        query_result: The result of the SQL execution, as a DataFrame.
        explanation: The natural language explanation of the results.
        error_message: A field to hold any error messages that occur.
        vanna_domain: The domain (e.g., 'students') the user is querying.
    """

    messages: List[BaseMessage]
    next_tool: str
    vanna_domain: str
    sql_query: Optional[str]
    query_result: Optional[pd.DataFrame]
    explanation: Optional[str]
    error_message: Optional[str]


VANNA_INSTANCES = {}
AVAILABLE_DOMAINS = []


def load_domain_metadata():
    """
    Loads the domain metadata from the external JSON file.
    """
    try:
        # The path is relative to the project root
        with open("domain_metadata.json", "r") as f:
            return json.load(f)
    except FileNotFoundError:
        print("ERROR: 'domain_metadata.json' not found. Please create it.")
        return {}
    except json.JSONDecodeError:
        print("ERROR: Could not decode 'domain_metadata.json'. Please check for syntax errors.")
        return {}


def initialize_llm_and_vanna():
    """
    Initializes the Gemini LLM and discovers available Vanna domains from Qdrant.
    This function should be called once when the application starts.
    """
    global AVAILABLE_DOMAINS

    domain_metadata = load_domain_metadata()
    if not domain_metadata:
        return []

    print("--- Initializing Gemini LLM ---")
    genai.configure(api_key=config.GEMINI_API_KEY)

    print("--- Discovering trained Vanna domains from Qdrant ---")
    try:
        qdrant_client = QdrantClient(url=config.QDRANT_URL, api_key=config.QDRANT_API_KEY)
        collections_response = qdrant_client.get_collections()
        all_collections = {
            c.name.replace("vanna_", "", 1): c
            for c in collections_response.collections
            if c.name.startswith("vanna_")
        }

        for domain_name, description in domain_metadata.items():
            if domain_name not in all_collections:
                print(
                    f"WARNING: Domain '{domain_name}' is in metadata but no matching 'vanna_{domain_name}' collection was found in Qdrant."
                )
                continue

            print(f"Initializing instance for domain: '{domain_name}'...")

            vanna_config = config.VANNA_CONFIG_DICT.copy()
            vanna_config["client"] = qdrant_client
            vanna_config["collection_name"] = f"vanna_{domain_name}"

            vn_instance = MyVanna(config=vanna_config)
            VANNA_INSTANCES[domain_name] = vn_instance

        AVAILABLE_DOMAINS = list(VANNA_INSTANCES.keys())

        if not AVAILABLE_DOMAINS:
            print("WARNING: No trainable domains with metadata were found in Qdrant.")
            return []

        print(
            f"--- Initialization complete. Found and loaded {len(AVAILABLE_DOMAINS)} domains with metadata. ---"
        )
        return AVAILABLE_DOMAINS

    except Exception as e:
        print(f"\nFATAL ERROR: Could not connect to Qdrant to discover domains: {e}")
        return []


def intent_router_node(state: GraphState) -> dict:
    """
    The supervisor node that decides the user's intent (SQL or General Chat).
    """
    print("--- Node: Intent Router ---")
    messages = state["messages"]
    last_message = messages[-1].content

    prompt = f"""You are an expert at routing user requests. Decide if the user's request requires the `SQL_AGENT` or is `GENERAL_CHAT`.

    CONVERSATION HISTORY:
    {messages}

    USER'S LATEST MESSAGE:
    "{last_message}"

    YOUR DECISION:"""

    router_agent_model = os.getenv("ROUTER_AGENT_MODEL", "gemini-1.5-pro")
    model = genai.GenerativeModel(router_agent_model)
    response = model.generate_content(prompt)
    decision = response.text.strip()
    print(f"Router decision: {decision}")
    if "SQL_AGENT" in decision:
        return {"next_tool": "SQL_AGENT"}
    else:
        return {"next_tool": "GENERAL_CHAT"}

def domain_router_node(state: GraphState) -> dict:
    """
    Analyzes the user's question to determine the most relevant Vanna domain.
    """
    print("--- Node: Domain Router ---")
    question = state["messages"][-1].content
    domain_metadata = load_domain_metadata()
    domain_options = "\n".join(
        [
            f"- **{name}**: {desc}"
            for name, desc in domain_metadata.items()
            if name in AVAILABLE_DOMAINS
        ]
    )
    prompt = f"""You are an expert at classifying a user's question into a specific data domain. Your answer must be ONLY ONE of the domain names from the list.

    DOMAINS:
    {domain_options}

    USER'S QUESTION:
    "{question}"

    MOST RELEVANT DOMAIN:"""

    domain_router_model = os.getenv("DOMAIN_ROUTER_MODEL", "gemini-1.5-pro")
    model = genai.GenerativeModel(domain_router_model)
    response = model.generate_content(prompt)
    chosen_domain = response.text.strip().replace("'", "").replace('"', "").replace("*", "")
    print(f"Domain Router decision: {chosen_domain}")
    if chosen_domain in AVAILABLE_DOMAINS:
        return {"vanna_domain": chosen_domain}
    else:
        print(f"WARNING: Router LLM returned an invalid domain. Fallback needed.")
        return {
            "error_message": f"I can't determine the correct data domain. Please be more specific about the topic (e.g., students, faculty)."
        }

def generate_sql_node(state: GraphState) -> dict:
    """
    Uses the appropriate Vanna instance to generate a SQL query.
    """
    print("--- Node: Generate SQL ---")
    question = state["messages"][-1].content
    domain = state["vanna_domain"]
    active_vanna = VANNA_INSTANCES.get(domain)
    if not active_vanna:
        return {"error_message": f"Error: Domain '{domain}' not found."}
    try:
        sql = active_vanna.get_sql(question)
        if not sql:
            return {"error_message": "Vanna could not generate SQL for this question."}
        print(f"Generated SQL: {sql}")
        return {"sql_query": sql}
    except Exception as e:
        return {"error_message": f"An error occurred during SQL generation: {e}"}

def execute_sql_node(state: GraphState) -> dict:
    """
    Executes the SQL query by calling the secure, air-gapped API.
    This node still includes the critical user approval step.
    """
    print("--- Node: Execute SQL (via Secure API) ---")
    sql = state["sql_query"]
    print("\n--- SQL Query for Review ---\n", sql, "\n----------------------------")
    try:
        choice = input("Do you want to send this query for execution? (y/n): ").lower()
        if choice != "y":
            return {"explanation": "Query execution cancelled by user."}
    except (KeyboardInterrupt, EOFError):
        return {"explanation": "Query execution cancelled by user."}
    print("Sending query to secure execution API...")
    try:
        api_url = config.SECURE_API_URL
        response = requests.post(f"{api_url}/execute-sql", json={"sql": sql})
        response.raise_for_status()
        result_json = response.json()
        result_str = pd.DataFrame(result_json).to_markdown(index=False)
        print("Query successful. Result preview:\n", result_str[:1000])
        return {"query_result": result_str}
    except requests.exceptions.HTTPError as http_err:
        error_detail = http_err.response.json().get("detail", str(http_err))
        error_msg = f"API Error: {error_detail}"
        print(error_msg)
        return {"error_message": error_msg}
    except Exception as e:
        error_msg = f"An unexpected error occurred: {e}"
        print(error_msg)
        return {"error_message": error_msg}

def explain_results_node(state: GraphState) -> dict:
    """
    Uses the LLM to explain the query results in natural language.
    """
    print("--- Node: Explain Results ---")
    question = state["messages"][-1].content
    query_result = state["query_result"]
    prompt = f"""You are a helpful data analyst. The user asked: '{question}'. The retrieved data is:
    ---
    {query_result}
    ---
    Please provide a brief, natural language summary of this data. If the data is empty, interpret it as "no results found" and state that clearly."""
    explain_agent_model = os.getenv("EXPLAIN_AGENT_MODEL", "gemini-1.5-flash")
    model = genai.GenerativeModel(explain_agent_model)
    response = model.generate_content(prompt)
    explanation = response.text.strip()
    print(f"Generated Explanation: {explanation}")
    return {"explanation": explanation}

def general_chat_node(state: GraphState) -> dict:
    """
    Handles general conversation that doesn't require database access.
    """
    print("--- Node: General Chat ---")
    question = state["messages"][-1].content
    prompt = f"You are a friendly AI assistant. A user is chatting with you. Here is their message: '{question}'. Respond conversationally."
    general_chat_model = os.getenv("GENERAL_CHAT_MODEL", "gemini-1.5-flash")
    model = genai.GenerativeModel(general_chat_model)
    response = model.generate_content(prompt)
    explanation = response.text.strip()
    print(f"Generated Chat Response: {explanation}")
    return {"explanation": explanation}

def build_graph():
    """
    Builds the LangGraph state machine.
    """
    print("--- Wiring the agent graph ---")
    workflow = StateGraph(GraphState)
    workflow.add_node("intent_router", intent_router_node)
    workflow.add_node("domain_router", domain_router_node)
    workflow.add_node("generate_sql", generate_sql_node)
    workflow.add_node("execute_sql", execute_sql_node)
    workflow.add_node("explain_results", explain_results_node)
    workflow.add_node("general_chat", general_chat_node)
    workflow.set_entry_point("intent_router")
    workflow.add_conditional_edges(
        "intent_router",
        lambda state: state["next_tool"],
        {"SQL_AGENT": "domain_router", "GENERAL_CHAT": "general_chat"},
    )
    workflow.add_conditional_edges(
        "domain_router",
        lambda state: "error" if state.get("error_message") else "continue",
        {"continue": "generate_sql", "error": END},
    )
    workflow.add_edge("generate_sql", "execute_sql")
    workflow.add_conditional_edges(
        "execute_sql",
        lambda state: "error" if state.get("error_message") else "success",
        {"success": "explain_results", "error": END},
    )
    workflow.add_edge("explain_results", END)
    workflow.add_edge("general_chat", END)
    agent_app = workflow.compile()
    print("--- Agent graph compiled successfully ---")
    return agent_app