import os
import sys
from typing import List, TypedDict, Optional
from langchain_core.messages import BaseMessage, HumanMessage
import requests
import pandas as pd
import google.generativeai as genai
from qdrant_client import QdrantClient
from sqlalchemy import create_engine, text
import json

from vanna_engine import config
from vanna_engine.my_vanna import MyVanna


class GraphState(TypedDict):
    """
    Represents the state of our chatbot agent.

    Attributes:
        messages: The entire conversation history.
        next_tool: The tool the router has decided to use next.
        sql_query: The SQL query generated by Vanna.
        query_result: The result of the SQL execution, as a DataFrame.
        explanation: The natural language explanation of the results.
        error_message: A field to hold any error messages that occur.
        vanna_domain: The domain (e.g., 'students') the user is querying.
    """
    messages: List[BaseMessage]
    next_tool: str
    vanna_domain: str
    sql_query: Optional[str]
    query_result: Optional[pd.DataFrame]
    explanation: Optional[str]
    error_message: Optional[str]

VANNA_INSTANCES = {}
AVAILABLE_DOMAINS = []

def load_domain_metadata():
    """
    Loads the domain metadata from the external JSON file.
    """
    try:
        # The path is relative to the project root
        with open('domain_metadata.json', 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print("ERROR: 'domain_metadata.json' not found. Please create it.")
        return {}
    except json.JSONDecodeError:
        print("ERROR: Could not decode 'domain_metadata.json'. Please check for syntax errors.")
        return {}

def initialize_llm_and_vanna():
    """
    Initializes the Gemini LLM and discovers available Vanna domains from Qdrant.
    This function should be called once when the application starts.
    """
    global AVAILABLE_DOMAINS

    domain_metadata = load_domain_metadata()
    if not domain_metadata:
        return []

    print("--- Initializing Gemini LLM ---")
    genai.configure(api_key=config.GEMINI_API_KEY)

    print("--- Discovering trained Vanna domains from Qdrant ---")
    try:
        qdrant_client = QdrantClient(url=config.QDRANT_URL, api_key=config.QDRANT_API_KEY)
        collections_response = qdrant_client.get_collections()
        all_collections = collections_response.collections
        all_collections = {c.name.replace("vanna_", "", 1): c for c in collections_response.collections if c.name.startswith("vanna_")}
        
        # --- MODIFICATION: We now iterate through our metadata ---
        for domain_name, description in domain_metadata.items():
            if domain_name not in all_collections:
                print(f"WARNING: Domain '{domain_name}' is in metadata but no matching 'vanna_{domain_name}' collection was found in Qdrant.")
                continue

            print(f"Initializing instance for domain: '{domain_name}'...")
            
            vanna_config = config.VANNA_CONFIG_DICT.copy()
            vanna_config["client"] = qdrant_client
            vanna_config["collection_name"] = f"vanna_{domain_name}"

            vn_instance = MyVanna(config=vanna_config)
            VANNA_INSTANCES[domain_name] = vn_instance
        
        # The list of available domains is now the keys from our metadata
        AVAILABLE_DOMAINS = list(VANNA_INSTANCES.keys())
        
        if not AVAILABLE_DOMAINS:
             print("WARNING: No trainable domains with metadata were found in Qdrant.")
             return []

        print(f"--- Initialization complete. Found and loaded {len(AVAILABLE_DOMAINS)} domains with metadata. ---")
        return AVAILABLE_DOMAINS

    except Exception as e:
        print(f"\nFATAL ERROR: Could not connect to Qdrant to discover domains: {e}")
        return []


def intent_router_node(state: GraphState) -> dict:
    """
    The supervisor node that decides the user's intent (SQL or General Chat).
    """
    print("--- Node: Intent Router ---")
    messages = state["messages"]
    last_message = messages[-1].content
    
    # Prompt for the router
    prompt = f"""You are an expert at routing user requests to the correct specialist agent. 
    Given the conversation history, you must decide which of the following tools to use next.
    Your answer must be one of: `SQL_AGENT`, `GENERAL_CHAT`.

    TOOLS:
    - `SQL_AGENT`: Use this when the user is asking a question that requires querying the database for specific data, numbers, or records.
    - `GENERAL_CHAT`: Use this for greetings, conversational filler, or questions about your capabilities that don't involve data.

    CONVERSATION HISTORY:
    {messages}

    USER'S LATEST MESSAGE:
    "{last_message}"

    YOUR DECISION:"""

    router_agent_model = os.getenv("ROUTER_AGENT_MODEL", "gemini-2.5-pro")
    print(f"Using router model: {router_agent_model}")
    model = genai.GenerativeModel(router_agent_model)
    response = model.generate_content(prompt)
    
    decision = response.text.strip()
    print(f"Router decision: {decision}")
    
    if "SQL_AGENT" in decision:
        return {"next_tool": "SQL_AGENT"}
    else:
        return {"next_tool": "GENERAL_CHAT"}


def generate_sql_node(state: GraphState) -> dict:
    """
    Uses the appropriate Vanna instance to generate a SQL query.
    """
    print("--- Node: Generate SQL ---")
    question = state["messages"][-1].content
    domain = state["vanna_domain"]
    
    active_vanna = VANNA_INSTANCES.get(domain)
    if not active_vanna:
        return {"error_message": f"Error: Domain '{domain}' not found."}
    
    try:
        sql = active_vanna.get_sql(question)
        if not sql:
            return {"error_message": "Vanna could not generate SQL for this question."}
        
        print(f"Generated SQL: {sql}")
        return {"sql_query": sql}
    except Exception as e:
        return {"error_message": f"An error occurred during SQL generation: {e}"}


def execute_sql_node(state: GraphState) -> dict:
    """
    Executes the SQL query by calling the secure, air-gapped API.
    This node still includes the critical user approval step.
    """
    print("--- Node: Execute SQL (via Secure API) ---")
    sql = state["sql_query"]
    
    # --- CRITICAL SAFETY STEP: User Approval ---
    print("\n--- SQL Query for Review ---")
    print(sql)
    print("----------------------------")
    try:
        choice = input("Do you want to send this query for execution? (y/n): ").lower()
        if choice != 'y':
            return {"explanation": "Query execution cancelled by user."}
    except (KeyboardInterrupt, EOFError):
        return {"explanation": "Query execution cancelled by user."}

    print("Sending query to secure execution API...")
    try:
        # THE NEW LOGIC: Call the API
        api_url = "http://127.0.0.1:8000/execute-sql" # This should be in config.py
        response = requests.post(api_url, json={"sql": sql})

        # Check for HTTP errors
        response.raise_for_status() 

        # Convert the JSON response back to a DataFrame, then to Markdown for the LLM
        result_json = response.json()
        if not result_json:
            return {"explanation": "The query executed successfully but returned no results."}
        
        df = pd.DataFrame(result_json)
        result_str = df.to_markdown(index=False)
        
        print("Query successful. Result preview:")
        print(result_str[:1000])
        
        return {"query_result": result_str}
        
    except requests.exceptions.HTTPError as http_err:
        # Extract the specific error message from the API's response
        error_detail = http_err.response.json().get('detail', str(http_err))
        error_msg = f"API Error: {error_detail}"
        print(error_msg)
        return {"error_message": error_msg}
    except Exception as e:
        error_msg = f"An unexpected error occurred: {e}"
        print(error_msg)
        return {"error_message": error_msg}
def explain_results_node(state: GraphState) -> dict:
    """
    Uses the LLM to explain the query results in natural language.
    """
    print("--- Node: Explain Results ---")
    question = state["messages"][-1].content
    query_result = state["query_result"]

    prompt = f"""You are a helpful data analyst. The user asked the question: '{question}'
    The following data was retrieved from the database:
    ---
    {query_result}
    ---
    Please provide a brief, natural language summary of this data that directly answers the user's question."""

    explain_agent_model = os.getenv("EXPLAIN_AGENT_MODEL", "gemini-2.5-flash")
    model = genai.GenerativeModel(explain_agent_model)
    response = model.generate_content(prompt)
    
    explanation = response.text.strip()
    print(f"Generated Explanation: {explanation}")
    
    return {"explanation": explanation}


def general_chat_node(state: GraphState) -> dict:
    """
    Handles general conversation that doesn't require database access.
    """
    print("--- Node: General Chat ---")
    question = state["messages"][-1].content
    
    prompt = f"You are a friendly AI assistant. A user is chatting with you. Here is their message: '{question}'. Respond conversationally."

    general_chat_model = os.getenv("GENERAL_CHAT_MODEL", "gemini-2.5-flash")
    model = genai.GenerativeModel(general_chat_model)
    response = model.generate_content(prompt)
    
    explanation = response.text.strip()
    print(f"Generated Chat Response: {explanation}")
    
    return {"explanation": explanation}

# --- Graph Wiring ---
from langgraph.graph import StateGraph, END

def build_graph():
    """
    Builds the LangGraph state machine.
    """
    print("--- Wiring the agent graph ---")
    workflow = StateGraph(GraphState)

    # Add all our functions as nodes in the graph
    workflow.add_node("intent_router", intent_router_node)
    workflow.add_node("domain_router", domain_router_node)
    workflow.add_node("generate_sql", generate_sql_node)
    workflow.add_node("execute_sql", execute_sql_node)
    workflow.add_node("explain_results", explain_results_node)
    workflow.add_node("general_chat", general_chat_node)

    # --- Define the Edges (The Flow) ---

    # The entry point is the intent_router
    workflow.set_entry_point("intent_router")

    # This is the conditional routing logic. Based on the output of the router_node,
    # the graph will decide which specialist agent to call.
    workflow.add_conditional_edges(
        "intent_router",
        lambda state: state["next_tool"],
        {
            "SQL_AGENT": "domain_router",
            "GENERAL_CHAT": "general_chat",
        },
    )

    # The SQL_AGENT is a multi-step sub-workflow. We define the linear
    # flow for this agent.
    workflow.add_edge("domain_router", "generate_sql")
    workflow.add_edge("generate_sql", "execute_sql")
    workflow.add_edge("execute_sql", "explain_results")
    
    # After the specialist agents have done their work, the conversation turn is over.
    # The graph will finish and return the final state.
    workflow.add_edge("explain_results", END)
    workflow.add_edge("general_chat", END)

    # Compile the workflow into a runnable application
    agent_app = workflow.compile()
    print("--- Agent graph compiled successfully ---")
    return agent_app


def select_domain(domains: list) -> str:
    """
    Displays a numbered menu for the user to select a domain.
    """
    print("\nPlease select a domain to query:")
    for i, domain in enumerate(domains):
        print(f"  {i + 1}: {domain}")
    
    while True:
        try:
            choice = input("Enter your choice (number): ")
            choice_num = int(choice)
            if 1 <= choice_num <= len(domains):
                return domains[choice_num - 1]
            else:
                print("Invalid number. Please try again.")
        except ValueError:
            print("Invalid input. Please enter a number.")
        except (KeyboardInterrupt, EOFError):
            print("\nExiting...")
            return None


def domain_router_node(state: GraphState) -> dict:
    """
    Analyzes the user's question to determine the most relevant Vanna domain.
    """
    print("--- Node: Domain Router ---")
    question = state["messages"][-1].content
    
    # Prompt for the domain router
    domain_metadata = load_domain_metadata()
    domain_options = "\n".join(
        [f"- **{name}**: {desc}" for name, desc in domain_metadata.items() if name in AVAILABLE_DOMAINS]
    )

    prompt = f"""You are an expert at classifying a user's question into a specific data domain.
    Based on the user's question, you must decide which of the following domains is the most relevant.
    Your answer must be ONLY ONE of the domain names from the list.

    DOMAINS:
    {domain_options}

    USER'S QUESTION:
    "{question}"

    MOST RELEVANT DOMAIN:"""

    domain_router_model = os.getenv("DOMAIN_ROUTER_MODEL", "gemini-2.5-pro")
    model = genai.GenerativeModel(domain_router_model)
    response = model.generate_content(prompt)
    
    chosen_domain = response.text.strip().replace("'", "").replace('"', '').replace("*", "")
    
    print(f"Domain Router decision: {chosen_domain}")
    
    if chosen_domain in AVAILABLE_DOMAINS:
        return {"vanna_domain": chosen_domain}
    else:
        # Fallback if the LLM hallucinates a domain or provides a conversational answer
        print(f"WARNING: Router LLM returned an invalid domain. Fallback needed.")
        return {"error_message": f"I can't determine the correct data domain for your question. Please try rephrasing it to be more specific about the topic (e.g., students, faculty)."}


def main():
    """
    The main application loop for the chatbot.
    """
    # Initialize everything once at the start
    available_domains = initialize_llm_and_vanna()
    if not available_domains:
        print("Could not find any Vanna domains. Please run the trainer first. Exiting.")
        return
        
    app = build_graph()

    print(f"\n--- Starting Chat ---")
    print("I can answer questions about the following domains:", available_domains)
    print("Type 'exit' or 'quit' to end the conversation.")

    # This will hold our full conversation history
    messages = []

    while True:
        try:
            user_input = input("\nYou: ")
            if user_input.lower() in ["exit", "quit"]:
                break

            # Append the user's message to the history
            messages.append(HumanMessage(content=user_input))

            initial_state = {
                "messages": messages,
            }

            # Invoke the LangGraph agent
            final_state = app.invoke(initial_state)

            # --- Display the result to the user ---
            if final_state.get("error_message"):
                print(f"\nAI (Error): {final_state['error_message']}")
                # Remove the last message from history if it caused an error
                messages.pop()
            elif final_state.get("explanation"):
                print(f"\nAI: {final_state['explanation']}")
                # We don't add the AI's response to the message history here,
                # as the router only needs the human questions to make decisions.
                # You could add it if you wanted a more conversational AI.
            else:
                print("\nAI: I'm sorry, an unexpected issue occurred.")
        
        except (KeyboardInterrupt, EOFError):
            break

    print("\n--- Conversation Ended ---")

if __name__ == "__main__":
    # Before running, make sure you have your secure API running in another terminal:
    # poetry run uvicorn secure_api.main:app --reload
    main()